server:
  port: 8080
spring:
  application:
    name: course_notifications_consumer
  datasource:
    url: jdbc:mysql://localhost:3306/users?serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update